-- Invoice request/discount workflow and payment receipt support

ALTER TABLE task_invoices
ADD COLUMN discount_type ENUM('none', 'percent', 'fixed') NOT NULL DEFAULT 'none' AFTER total_amount,
ADD COLUMN discount_value DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER discount_type,
ADD COLUMN discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER discount_value,
ADD COLUMN adjusted_on TIMESTAMP NULL DEFAULT NULL AFTER discount_amount,
ADD COLUMN adjusted_by INT UNSIGNED DEFAULT NULL AFTER adjusted_on,
ADD KEY idx_task_invoices_discount_type (discount_type),
ADD CONSTRAINT fk_task_invoices_adjusted_by FOREIGN KEY (adjusted_by) REFERENCES users (id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS support_ticket_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ticket_id INT UNSIGNED NOT NULL,
  company_id INT UNSIGNED NOT NULL,
  client_id INT UNSIGNED NOT NULL,
  request_type ENUM('invoice_request', 'discount_request', 'credit_period_request', 'advance_payment_request', 'partial_payment_request') NOT NULL,
  target_task_id INT UNSIGNED DEFAULT NULL,
  target_stage_id INT UNSIGNED DEFAULT NULL,
  target_invoice_id INT UNSIGNED DEFAULT NULL,
  requested_amount DECIMAL(12,2) DEFAULT NULL,
  requested_percent DECIMAL(6,2) DEFAULT NULL,
  requested_due_on DATE DEFAULT NULL,
  decision_status ENUM('pending', 'approved', 'rejected', 'negotiation', 'deferred') NOT NULL DEFAULT 'pending',
  approved_amount DECIMAL(12,2) DEFAULT NULL,
  approved_percent DECIMAL(6,2) DEFAULT NULL,
  approved_due_on DATE DEFAULT NULL,
  applied_invoice_id INT UNSIGNED DEFAULT NULL,
  admin_note TEXT DEFAULT NULL,
  processed_by INT UNSIGNED DEFAULT NULL,
  processed_on TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_support_ticket_request_ticket (ticket_id),
  KEY idx_support_ticket_requests_company (company_id),
  KEY idx_support_ticket_requests_client (client_id),
  KEY idx_support_ticket_requests_type (request_type),
  KEY idx_support_ticket_requests_target_invoice (target_invoice_id),
  CONSTRAINT fk_support_ticket_requests_ticket FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_support_ticket_requests_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  CONSTRAINT fk_support_ticket_requests_client FOREIGN KEY (client_id) REFERENCES client_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_support_ticket_requests_task FOREIGN KEY (target_task_id) REFERENCES client_tasks (id) ON DELETE SET NULL,
  CONSTRAINT fk_support_ticket_requests_stage FOREIGN KEY (target_stage_id) REFERENCES task_stages (id) ON DELETE SET NULL,
  CONSTRAINT fk_support_ticket_requests_invoice FOREIGN KEY (target_invoice_id) REFERENCES task_invoices (id) ON DELETE SET NULL,
  CONSTRAINT fk_support_ticket_requests_applied_invoice FOREIGN KEY (applied_invoice_id) REFERENCES task_invoices (id) ON DELETE SET NULL,
  CONSTRAINT fk_support_ticket_requests_processed_by FOREIGN KEY (processed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_payment_receipts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_request_id INT UNSIGNED NOT NULL,
  invoice_id INT UNSIGNED NOT NULL,
  company_id INT UNSIGNED NOT NULL,
  client_id INT UNSIGNED DEFAULT NULL,
  receipt_no VARCHAR(60) NOT NULL,
  amount_received DECIMAL(12,2) NOT NULL,
  payment_method VARCHAR(100) DEFAULT NULL,
  payment_reference VARCHAR(190) DEFAULT NULL,
  received_on DATE NOT NULL,
  notes TEXT DEFAULT NULL,
  created_by INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_invoice_payment_receipts_no (receipt_no),
  KEY idx_invoice_payment_receipts_request (payment_request_id),
  KEY idx_invoice_payment_receipts_invoice (invoice_id),
  KEY idx_invoice_payment_receipts_company (company_id),
  CONSTRAINT fk_invoice_payment_receipts_request FOREIGN KEY (payment_request_id) REFERENCES invoice_payment_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_invoice_payment_receipts_invoice FOREIGN KEY (invoice_id) REFERENCES task_invoices (id) ON DELETE CASCADE,
  CONSTRAINT fk_invoice_payment_receipts_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
  CONSTRAINT fk_invoice_payment_receipts_client FOREIGN KEY (client_id) REFERENCES client_profiles (id) ON DELETE SET NULL,
  CONSTRAINT fk_invoice_payment_receipts_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
