ALTER TABLE vouchers
  ADD COLUMN IF NOT EXISTS voucher_date DATE DEFAULT NULL AFTER voucher_no,
  ADD COLUMN IF NOT EXISTS party_id INT UNSIGNED DEFAULT NULL AFTER source_id,
  ADD COLUMN IF NOT EXISTS reference_no VARCHAR(120) DEFAULT NULL AFTER party_id,
  ADD KEY IF NOT EXISTS idx_vouchers_date (company_id, fiscal_year_id, voucher_date),
  ADD KEY IF NOT EXISTS idx_vouchers_party (party_id);

CREATE TABLE IF NOT EXISTS accounting_parties (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id INT UNSIGNED NOT NULL,
  ledger_id INT UNSIGNED DEFAULT NULL,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(190) NOT NULL,
  party_type ENUM('customer', 'supplier', 'both', 'other') NOT NULL DEFAULT 'both',
  pan_no VARCHAR(60) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  phone VARCHAR(80) DEFAULT NULL,
  billing_address TEXT DEFAULT NULL,
  opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  opening_balance_type ENUM('debit', 'credit') NOT NULL DEFAULT 'debit',
  credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_accounting_parties_company_code (company_id, code),
  KEY idx_accounting_parties_company_type (company_id, party_type),
  KEY idx_accounting_parties_ledger (ledger_id),
  CONSTRAINT fk_accounting_parties_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_accounting_parties_ledger FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id INT UNSIGNED NOT NULL,
  ledger_id INT UNSIGNED DEFAULT NULL,
  sku VARCHAR(80) NOT NULL,
  name VARCHAR(190) NOT NULL,
  item_type ENUM('stock', 'service', 'raw_material', 'finished_good', 'consumable') NOT NULL DEFAULT 'stock',
  unit VARCHAR(40) NOT NULL DEFAULT 'pcs',
  hs_code VARCHAR(80) DEFAULT NULL,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 13.00,
  sales_rate DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  purchase_rate DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  opening_qty DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  reorder_level DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_inventory_items_company_sku (company_id, sku),
  KEY idx_inventory_items_company_type (company_id, item_type),
  KEY idx_inventory_items_ledger (ledger_id),
  CONSTRAINT fk_inventory_items_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_items_ledger FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id INT UNSIGNED NOT NULL,
  fiscal_year_id INT UNSIGNED DEFAULT NULL,
  item_id INT UNSIGNED NOT NULL,
  voucher_id INT UNSIGNED DEFAULT NULL,
  transaction_type ENUM('opening', 'purchase', 'sale', 'sales_return', 'purchase_return', 'adjustment', 'consume', 'produce') NOT NULL DEFAULT 'adjustment',
  ref_no VARCHAR(120) DEFAULT NULL,
  transaction_date DATE NOT NULL,
  qty_in DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  qty_out DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  rate DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_inventory_transactions_company_date (company_id, transaction_date),
  KEY idx_inventory_transactions_item (item_id),
  KEY idx_inventory_transactions_voucher (voucher_id),
  CONSTRAINT fk_inventory_transactions_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_transactions_fiscal_year FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years(id) ON DELETE SET NULL,
  CONSTRAINT fk_inventory_transactions_item FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_transactions_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS manufacturing_orders (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id INT UNSIGNED NOT NULL,
  fiscal_year_id INT UNSIGNED DEFAULT NULL,
  order_no VARCHAR(80) NOT NULL,
  finished_item_id INT UNSIGNED NOT NULL,
  quantity DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  status ENUM('draft', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'draft',
  started_on DATE DEFAULT NULL,
  completed_on DATE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_manufacturing_orders_company_no (company_id, order_no),
  KEY idx_manufacturing_orders_company_status (company_id, status),
  KEY idx_manufacturing_orders_finished_item (finished_item_id),
  CONSTRAINT fk_manufacturing_orders_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_manufacturing_orders_fiscal_year FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years(id) ON DELETE SET NULL,
  CONSTRAINT fk_manufacturing_orders_finished_item FOREIGN KEY (finished_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS manufacturing_order_inputs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  manufacturing_order_id INT UNSIGNED NOT NULL,
  item_id INT UNSIGNED NOT NULL,
  quantity DECIMAL(14,3) NOT NULL DEFAULT 0.000,
  rate DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_manufacturing_order_inputs_order (manufacturing_order_id),
  KEY idx_manufacturing_order_inputs_item (item_id),
  CONSTRAINT fk_manufacturing_order_inputs_order FOREIGN KEY (manufacturing_order_id) REFERENCES manufacturing_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_manufacturing_order_inputs_item FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
