-- Migration 037: Fixed Asset Register foundation (IAS 16 / IAS 38 / IFRS 16 /
-- IFRS 5 / IAS 36). Entirely new module — no existing table is touched.
-- Backs app/fixed_asset_engine.php with persistent asset master, depreciation &
-- lease schedules, impairment tests, and scoped ledger mappings.

CREATE TABLE IF NOT EXISTS `asset_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `asset_class` ENUM('ppe', 'intangible', 'rou', 'investment_property', 'cwip') NOT NULL DEFAULT 'ppe',
  `default_method` ENUM('straight_line', 'diminishing_balance', 'units') NOT NULL DEFAULT 'straight_line',
  `default_life_months` INT UNSIGNED NOT NULL DEFAULT 60,
  `default_rate_pct` DECIMAL(6,3) NOT NULL DEFAULT 0.000,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_asset_categories_company_name` (`company_id`, `name`),
  KEY `idx_asset_categories_company_class` (`company_id`, `asset_class`),
  CONSTRAINT `fk_asset_categories_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fixed_assets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED DEFAULT NULL,
  `parent_asset_id` INT UNSIGNED DEFAULT NULL COMMENT 'component accounting',
  `asset_code` VARCHAR(80) NOT NULL,
  `barcode` VARCHAR(120) DEFAULT NULL,
  `name` VARCHAR(190) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `asset_class` ENUM('ppe', 'intangible', 'rou', 'investment_property', 'cwip') NOT NULL DEFAULT 'ppe',
  `ifrs_class` VARCHAR(80) DEFAULT NULL,
  `intangible_life` ENUM('finite', 'indefinite') DEFAULT NULL,
  `location` VARCHAR(150) DEFAULT NULL,
  `department` VARCHAR(120) DEFAULT NULL,
  `custodian` VARCHAR(150) DEFAULT NULL,
  `supplier` VARCHAR(190) DEFAULT NULL,
  `purchase_ref` VARCHAR(120) DEFAULT NULL,
  `purchase_date` DATE DEFAULT NULL,
  `available_for_use_date` DATE DEFAULT NULL,
  `depreciation_start_date` DATE DEFAULT NULL,
  `cost` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `directly_attributable_cost` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `restoration_provision` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `residual_value` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `useful_life_months` INT UNSIGNED NOT NULL DEFAULT 60,
  `depreciation_method` ENUM('straight_line', 'diminishing_balance', 'units') NOT NULL DEFAULT 'straight_line',
  `diminishing_rate_pct` DECIMAL(6,3) NOT NULL DEFAULT 0.000,
  `total_units` DECIMAL(18,3) NOT NULL DEFAULT 0.000,
  `accumulated_depreciation` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `accumulated_impairment` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `revaluation_reserve` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `carrying_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `tax_base` DECIMAL(18,2) DEFAULT NULL,
  `status` ENUM('draft', 'active', 'held_for_sale', 'disposed', 'fully_depreciated') NOT NULL DEFAULT 'draft',
  `disposed_on` DATE DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_fixed_assets_company_code` (`company_id`, `asset_code`),
  KEY `idx_fixed_assets_company_status` (`company_id`, `status`),
  KEY `idx_fixed_assets_category` (`category_id`),
  KEY `idx_fixed_assets_parent` (`parent_asset_id`),
  CONSTRAINT `fk_fixed_assets_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_fixed_assets_category` FOREIGN KEY (`category_id`) REFERENCES `asset_categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fixed_assets_parent` FOREIGN KEY (`parent_asset_id`) REFERENCES `fixed_assets` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `asset_depreciation_schedule` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `period_no` INT UNSIGNED NOT NULL,
  `period_date` DATE NOT NULL,
  `depreciation` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `accumulated` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `carrying` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `voucher_id` INT UNSIGNED DEFAULT NULL,
  `posted` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_asset_dep_period` (`asset_id`, `period_no`),
  KEY `idx_asset_dep_company_date` (`company_id`, `period_date`),
  KEY `idx_asset_dep_voucher` (`voucher_id`),
  CONSTRAINT `fk_asset_dep_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_dep_asset` FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_dep_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `vouchers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lease_liabilities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED DEFAULT NULL COMMENT 'linked ROU asset',
  `contract_ref` VARCHAR(120) NOT NULL,
  `commencement_date` DATE NOT NULL,
  `term_months` INT UNSIGNED NOT NULL DEFAULT 12,
  `payment` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `payment_timing` ENUM('advance', 'arrears') NOT NULL DEFAULT 'arrears',
  `discount_rate_annual` DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  `initial_liability` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `initial_direct_costs` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `prepayments` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `incentives` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `restoration` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `rou_initial` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `status` ENUM('draft', 'active', 'closed') NOT NULL DEFAULT 'draft',
  `created_by` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_lease_company` (`company_id`, `status`),
  KEY `idx_lease_asset` (`asset_id`),
  CONSTRAINT `fk_lease_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_lease_asset` FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lease_schedule_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lease_id` INT UNSIGNED NOT NULL,
  `period_no` INT UNSIGNED NOT NULL,
  `period_date` DATE NOT NULL,
  `opening` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `interest` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `payment` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `principal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `closing` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `voucher_id` INT UNSIGNED DEFAULT NULL,
  `posted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_lease_line_period` (`lease_id`, `period_no`),
  KEY `idx_lease_line_voucher` (`voucher_id`),
  CONSTRAINT `fk_lease_line_lease` FOREIGN KEY (`lease_id`) REFERENCES `lease_liabilities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `asset_impairments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `asset_id` INT UNSIGNED NOT NULL,
  `test_date` DATE NOT NULL,
  `kind` ENUM('impairment', 'reversal', 'held_for_sale', 'revaluation') NOT NULL DEFAULT 'impairment',
  `carrying_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `fair_value_less_costs` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `value_in_use` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `recoverable_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `impairment_loss` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `reversal` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `evidence` VARCHAR(255) DEFAULT NULL,
  `voucher_id` INT UNSIGNED DEFAULT NULL,
  `approved_by` INT UNSIGNED DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_asset_imp_asset_date` (`asset_id`, `test_date`),
  KEY `idx_asset_imp_voucher` (`voucher_id`),
  CONSTRAINT `fk_asset_imp_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_imp_asset` FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_imp_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `vouchers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `asset_ledger_mappings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `scope` ENUM('global', 'category', 'asset') NOT NULL DEFAULT 'global',
  `category_id` INT UNSIGNED DEFAULT NULL,
  `asset_id` INT UNSIGNED DEFAULT NULL,
  `purpose` VARCHAR(60) NOT NULL,
  `ledger_id` INT UNSIGNED NOT NULL,
  `effective_date` DATE DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_asset_mapping_scope` (`company_id`, `scope`, `category_id`, `asset_id`, `purpose`),
  KEY `idx_asset_mapping_lookup` (`company_id`, `purpose`, `scope`),
  KEY `idx_asset_mapping_ledger` (`ledger_id`),
  CONSTRAINT `fk_asset_mapping_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_mapping_category` FOREIGN KEY (`category_id`) REFERENCES `asset_categories` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_mapping_asset` FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_asset_mapping_ledger` FOREIGN KEY (`ledger_id`) REFERENCES `ledgers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
